// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbrZ8HQNVriMPOjEnUTEGbPGtwYg-i-Zo',
    appId: '1:386572767615:web:3c31e736efa5951151ca4a',
    messagingSenderId: '386572767615',
    projectId: 'refika-7a54b',
    authDomain: 'refika-7a54b.firebaseapp.com',
    storageBucket: 'refika-7a54b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlc3yKrP-YdJIuOVlsQdYc6QDlvZlFmxs',
    appId: '1:386572767615:android:64df0ed314fd0c0851ca4a',
    messagingSenderId: '386572767615',
    projectId: 'refika-7a54b',
    storageBucket: 'refika-7a54b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNeoEyIldngRFd9VD4n95Lv0JA2mqNcNs',
    appId: '1:386572767615:ios:e1edc7849c08dce051ca4a',
    messagingSenderId: '386572767615',
    projectId: 'refika-7a54b',
    storageBucket: 'refika-7a54b.appspot.com',
    iosClientId: '386572767615-dlutkn5g7g5ucd75muj4jco6i5v2m48p.apps.googleusercontent.com',
    iosBundleId: 'com.example.refikaApp',
  );
}
